### ISSUE TITLE
Textures should be of a power of two

### ISSUE THREAD

**Issue by 526avijitgupta** [MozVR/sechelt#10]
![screenshot from 2015-10-01 14 25 48](https://cloud.githubusercontent.com/assets/7583815/10216667/61f8c5f2-6848-11e5-9834-35bfe5f889d2.png)
THREE.js throws a warning for the texture size (since the texture size is expected to be a power of two).

From the _three.js code_:

``` javascript
if ( texture.minFilter !== THREE.NearestFilter && texture.minFilter !== THREE.LinearFilter ) {
  console.warn( 'THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter. ( ' + texture.sourceFile + ' )' );
 }
```

Can be easily gotten rid of by setting `texture.minFilter = THREE.minFilter`

**Comment by cvan** [comment]
The warnings could be supressed, but IMO the fix should be to make the textures be of POT.

**Comment by greengiant83** [comment]
Since this is the web and we may be sourcing images for arbitrary sources, and because it three.js can adequately deal with the  NPOT textures, I don't see the need for a warning. At the very least it would be nice to be able to suppress it so it doesn't clutter up the console with useless noise.

**Comment by trusktr** [comment]
Seems lately, instead of throwing a warning, Three will resize your textures to lower quality to. Is it encouragement to go use power-of-two? 

This is what I see in the console:

```
THREE.WebGLRenderer: image is not power of two (1000x500). Resized to 512x256
```

and the downsized image looks ugly.

**Comment by mrdoob** [comment]
@trusktr why don't you use the three.js forum for this kind of questions?

**Comment by trusktr** [comment]
Too easy to comment on the existing thread.

Defaulting to `LinearFilter` would be best for all us newbs! =)

**Comment by mrdoob** [comment]
> Too easy to comment on the existing thread.

:(

> Defaulting to `LinearFilter` would be best for all us newbs! =)

That would result in a slower performance.

**Comment by trusktr** [comment]
> That would result in a slower performance.

Newbs don't care, they just want easy awesome at first.

**Comment by pjho** [comment]
[Heres some reading for Newbs that do care](https://www.katsbits.com/tutorials/textures/make-better-textures-correct-size-and-power-of-two.php) 😄 

From the article

> ... [ensure] 2D image assets conform to regulated sizes and dimensions, which typically manifest as; 1) width/height being divisible by "8", and/or 2) width/height that can be doubled-up or divided-down by "2". In other words any image that is "8", "16", "32", "64", "128", "256", "512", "1024", "2048" (or higher for more modern games) pixels in one or more width/height direction, is considered valid and properly optimised for quick loading into a game and processing into memory. These two simple points in practice means texture assets being "64 x 64", "128 x 64", "2048 x 512" and so on.
