### ISSUE TITLE
Stop assuming 60 fps for rAF

### ISSUE THREAD

**Issue by cvan** [MozVR/sechelt#12]
[Here](https://github.com/MozVR/sechelt/blob/6054e36/js/sechelt.js#L330). Need to actually look at the current time and pace things appropriately.

I've used [`request-interval`](https://www.npmjs.com/package/request-interval) with good success in the past.

**Comment by mrdoob** [comment]
Where is the 60 fps assumption?

**Comment by cvan** [comment]
@caseyyee can you weigh in here? I forgot what we talking about for this.

**Comment by caseyyee** [comment]
We're not tied to 60fps.   I think your probably referring to the time delta that is being passed in.
