### ISSUE TITLE
Sechelt demo is not rendering correctly on iOS

### ISSUE THREAD

**Issue by autonome** [MozVR/sechelt#15]
Safari iOS: Super pixellated, and the goggles aren't rendering. See screenshot below.
Firefox iOS: Black screen.

**Comment by mrdoob** [comment]
Missing screenshot?

**Comment by autonome** [comment]
Waiting for Dropbox on iPhone to sync my stuff. Yay cloud.

**Comment by autonome** [comment]
![2016-01-27 10 18 57](https://cloud.githubusercontent.com/assets/50103/12625037/c7b35a6a-c4e6-11e5-8606-93a82e4a3bc3.png)

**Comment by mrdoob** [comment]
Oh. I think that stated happening with the latest iOS...

**Comment by EvanKnowles** [comment]
I'm also having issues - renders fine when not in VR mode, switching to VR mode blanks out the except for a gray area. Switching back to standard results in the image only being shown on the right hand side of the screen, like it was still rendering two viewpoints. Rotating the device to portrait and then landscape again fixes normal mode.

![img_5437](https://cloud.githubusercontent.com/assets/4895661/12929758/2219a702-cf7d-11e5-879f-da338dc9914b.jpg)
![img_5438](https://cloud.githubusercontent.com/assets/4895661/12929757/2218670c-cf7d-11e5-8a71-63446b4dffe7.jpg)
